##############################################################################
# This will be the function to set up the game
#  - Instantiate each power
#  - Insantiate each territory along with its adjacent territories
#  - Put each territory into its respective power
#  - Put units in their respective territories
#       -If you don't know about list comprehensions yet, let's talk before you do this
#       -Every unit has to be instantiated with its power, e.g. Units.Infantry(power=USSR)
#               ---Nathan
##############################################################################

import Powers
import Territories
import Units as u

def setup():
    
    #Create Powers
    USSR = Powers.Power("Allies", [], 24, "USSR")
    Germany = Powers.Power("Axis", [], 32, "Germany")
    UK = Powers.Power("Allies", [], 30, "UK")
    Japan = Powers.Power("Axis", [], 25, "Japan")
    US = Powers.Power("Allies", [], 36, "US")
    
    #Create Land Territories
    eastern_canada = Territories.Land("UK", [], [u.Tank(power=UK)], "Eastern Canada", 3, 0, False)
    eastern_usa = Territories.Land("US", [], [u.Infantry(power=US) for x in range(2)] + [u.Bomber(power=US), u.Fighter(power=US), u.Tank(power=US), u.AntiAircraft(power=US)], "Eastern USA", 12, 2, True)
    west_indies = Territories.Land("US", [], [], "West Indies", 1, 0, False)
    panama = Territories.Land("US", [], [], "Panama", 1, 0, False)
    venezuela = Territories.Land("neutral", [], [], "Venezuela", 0, 0, False)
    peru = Territories.Land("neutral", [], [], "Peru", 0, 0, False)
    argentina = Territories.Land("neutral", [], [], "Argentina", 0, 0, False)
    brazil = Territories.Land("US", [], [], "Brazil", 3, 0, False)
    united_kingdom = Territories.Land("UK", [], [u.Infantry(power=UK) for x in range(2)] + [u.Tank(power=UK), u.AntiAircraft(power=UK)], "United Kingdom", 8, 2, True)
    spain = Territories.Land("neutral", [], [], "Spain", 0, 0, False)
    gibraltar = Territories.Land("UK", [], [], "Gibraltar", 0, 0, False)
    western_europe = Territories.Land("Germany", [], [u.Infantry(power=Germany) for x in range(2)] + [u.Tank(power=Germany) for x in range(2)] + [u.Fighter(power=Germany), u.AntiAircraft(power=Germany)], "Western Europe", 6, 0, True)
    switz = Territories.Land("neutral", [], [], "Switz", 0, 0, False)
    finland = Territories.Land("Germany", [], [u.Infantry(power=Germany) for x in range(3)] + [u.Tank(power=Germany), u.Fighter(power=Germany)], "Finland", 2, 0, False)
    sweden = Territories.Land("neutral", [], [], "Sweden", 0, 0, False)
    germany = Territories.Land("Germany", [], [u.Infantry(power=Germany) for x in range(4)] + [u.Tank(power=Germany) for x in range(2)] + [u.AntiAircraft(power=Germany)], "Germany", 10, 2, True)
    southern_europe = Territories.Land("Germany", [], [u.Infantry(power=Germany) for x in range(2)] + [u.Tank(power=Germany, u.AntiAircraft(power=Germay)], "Southern Europe", 6, 2, False)
    eastern_europe = Territories.Land("Germany", [], [u.Infantry(power=Germany) for x in range(3)] + [u.Tank(power=Germany), u.Fighter(power=Germany)], "Eastern Europe", 3, 0, False)
    ukraine = Territories.Land("Germany", [], [u.Infantry(power=Germany) for x in range(3)] + [u.Tank(power=Germany) for x in range(2)] + [u.Fighter(power=Germany)], "Ukraine", 3, 0, False)
    algeria = Territories.Land("Germany", [], [u.Infantry(power=Germany)], "Algeria", 1, 0, False)
    libya = Territories.Land("Germany", [], [u.Infantry(power=Germany), u.Tank(power=Germany)], "Libya", 1, 0, False)
    west_africa = Territories.Land("UK", [], [], "West Africa", 1, 0, False)
    equatorial_africa = Territories.Land("UK", [], [], "Equatorial Africa", 1, 0, False)
    egypt = Territories.Land("UK", [], [u.Infantry(power=UK), u.Tank(power=UK)], "Egypt", 2, 0, False)
    congo = Territories.Land("UK", [], [], "Congo", 1, 0, False)
    east_africa = Territories.Land("UK", [], [], "East Africa", 1, 0, False)
    angola = Territories.Land("neutral", [], [], "Angola", 0, 0, False)
    kenya = Territories.Land("UK", [], [], "Kenya", 1, 0, False)
    south_africa = Territories.Land("UK", [], [u.Infantry(power=UK)], "South Africa", 2, 0, False)
    #This is the extent of Nathan's unit initialization
    mozambique = Territories.Land("neutral", [], [], "Mozambique", 0, 0, False)
    madagascar = Territories.Land("UK", [], [], "Madagascar", 1, 0, False)
    karelia = Territories.Land("USSR", [], [], "Karelia", 3, 2, False)
    caucasus = Territories.Land("USSR", [], [], "Caucasus", 3, 0, False)
    turkey = Territories.Land("neutral", [], [], "Turkey", 0, 0, False)
    syria = Territories.Land("UK", [], [], "Syria", 1, 0, False)
    persia = Territories.Land("UK", [], [], "Persia", 1, 0, False)
    saudi_arabia = Territories.Land("neutral", [], [], "Saudi Arabia", 0, 0, False)
    russia = Territories.Land("USSR", [], [], "Russia", 8, 2, True)
    kazakh = Territories.Land("USSR", [], [], "Kazakh", 2, 0, False)
    afghan = Territories.Land("neutral", [], [], "Afghan", 0, 0, False)
    india = Territories.Land("UK", [], [], "India", 3, 0, False)
    evenki = Territories.Land("USSR", [], [], "Evenki", 2, 0, False)
    novosibirsk = Territories.Land("USSR", [], [], "Novosibirsk", 2, 0, False)
    sinkiang = Territories.Land("US", [], [], "Sinkiang", 2, 0, False)
    yakut = Territories.Land("USSR", [], [], "Yakut", 2, 0, False)
    mongolia = Territories.Land("neutral", [], [], "Mongolia", 0, 0, False)
    china = Territories.Land("US", [], [], "China", 2, 0, False)
    indochina = Territories.Land("Japan", [], [], "Indochina", 3, 0, False)
    kwangtung = Territories.Land("Japan", [], [], "Kwantung", 3, 0, False)
    manchuria = Territories.Land("Japan", [], [], "Manchuria", 3, 0, False)
    soviet_east = Territories.Land("USSR", [], [], "Soviet East", 2, 0, False)
    east_indies = Territories.Land("Japan", [], [], "East Indies", 2, 0, False)
    borneo = Territories.Land("Japan", [], [], "Borneo", 1, 0, False)
    philippine_islands = Territories.Land("Japan", [], [], "Philippine Islands", 3, 0, False)
    australia = Territories.Land("UK", [], [], "Australia", 2, 0, False)
    new_guinea = Territories.Land("Japan", [], [], "New Guinea", 1, 0, False)
    caroline_islands = Territories.Land("Japan", [], [], "Caroline Islands", 0, 0, False)
    new_zealand = Territories.Land("UK", [], [], "New Zealand", 1, 0, False)
    solomon_island = Territories.Land("Japan", [], [], "Solomon Island", 0, 0, False)
    okinawa = Territories.Land("Japan", [], [], "Okinawa", 0, 0, False)
    wake_island = Territories.Land("Japan", [], [], "Wake Island", 0, 0, False)
    japan = Territories.Land("Japan", [], [], "Japan", 8, 0, True)
    alaska = Territories.Land("US", [], [], "Alaska", 2, 0, False)
    midway_island = Territories.Land("US", [], [], "Midway Island", 0, 0, False)
    hawaiian_islands = Territories.Land("US", [], [], "Hawaiian Islands", 1, 0, False)
    western_canada = Territories.Land("UK", [], [], "Wester Canada", 1, 0, False)
    western_usa = Territories.Land("US", [], [], "Western USA", 10, 2, False)
    mexico = Territories.Land("US", [], [], "Mexico", 2, 0, False)
    
    
    #Create Sea Territories
    zone_1 = Territories.Sea("neutral", [], [], "zone_1", 0)
    zone_2 = Territories.Sea("US", [], [], "zone_2", 0)
    zone_3 = Territories.Sea("neutral", [], [], "zone_3", 0)
    zone_4 = Territories.Sea("neutral", [], [], "zone_4", 0)
    zone_5 = Territories.Sea("neutral", [], [], "zone_5", 0)
    zone_6 = Territories.Sea("UK", [], [], "zone_6", 0)
    zone_7 = Territories.Sea("neutral", [], [], "zone_7", 0)
    zone_8 = Territories.Sea("neutral", [], [], "zone_8", 0)
    zone_9 = Territories.Sea("neutral", [], [], "zone_9", 0)
    zone_10 = Territories.Sea("UK", [], [], "zone_10", 0)
    zone_11 = Territories.Sea("Germany", [], [], "zone_11", 0)
    zone_12 = Territories.Sea("neutral", [], [], "zone_12", 0)
    zone_13 = Territories.Sea("neutral", [], [], "zone_13", 0)
    zone_14 = Territories.Sea("neutral", [], [], "zone_14", 0)
    zone_15 = Territories.Sea("neutral", [], [], "zone_15", 0)
    zone_16 = Territories.Sea("USSR", [], [], "zone_16", 0)
    zone_17 = Territories.Sea("Germany", [], [], "zone_17", 0)
    zone_18 = Territories.Sea("UK", [], [], "zone_18", 0)
    zone_19 = Territories.Sea("Germany", [], [], "zone_19", 0)
    zone_20 = Territories.Sea("neutral", [], [], "zone_20", 0)
    zone_21 = Territories.Sea("UK", [], [], "zone_21", 0)
    zone_22 = Territories.Sea("neutral", [], [], "zone_22", 0)
    zone_23 = Territories.Sea("neutral", [], [], "zone_23", 0)
    zone_24 = Territories.Sea("neutral", [], [], "zone_24", 0)
    zone_25 = Territories.Sea("neutral", [], [], "zone_25", 0)
    zone_26 = Territories.Sea("neutral", [], [], "zone_26", 0)
    zone_27 = Territories.Sea("UK", [], [], "zone_27", 0)
    zone_28 = Territories.Sea("neutral", [], [], "zone_28", 0)
    zone_29 = Territories.Sea("neutral", [], [], "zone_29", 0)
    zone_30 = Territories.Sea("neutral", [], [], "zone_30", 0)
    zone_31 = Territories.Sea("neutral", [], [], "zone_31", 0)
    zone_32 = Territories.Sea("neutral", [], [], "zone_32", 0)
    zone_33 = Territories.Sea("Japan", [], [], "zone_33", 0)
    zone_34 = Territories.Sea("neutral", [], [], "zone_34", 0)
    zone_35 = Territories.Sea("neutral", [], [], "zone_35", 0)
    zone_36 = Territories.Sea("Japan", [], [], "zone_36", 0)
    zone_37 = Territories.Sea("neutral", [], [], "zone_37", 0)
    zone_38 = Territories.Sea("Japan", [], [], "zone_38", 0)
    zone_39 = Territories.Sea("neutral", [], [], "zone_39", 0)
    zone_40 = Territories.Sea("neutral", [], [], "zone_40", 0)
    zone_41 = Territories.Sea("neutral", [], [], "zone_41", 0)
    zone_42 = Territories.Sea("neutral", [], [], "zone_42", 0)
    zone_43 = Territories.Sea("neutral", [], [], "zone_43", 0)
    zone_44 = Territories.Sea("Japan", [], [], "zone_44", 0)
    zone_45 = Territories.Sea("neutral", [], [], "zone_45", 0)
    zone_46 = Territories.Sea("neutral", [], [], "zone_46", 0)
    zone_47 = Territories.Sea("neutral", [], [], "zone_47", 0)
    zone_48 = Territories.Sea("US", [], [], "zone_48", 0)
    zone_49 = Territories.Sea("US", [], [], "zone_49", 0)
    zone_50 = Territories.Sea("neutral", [], [], "zone_50", 0)
    zone_51 = Territories.Sea("neutral", [], [], "zone_51", 0)
    zone_52 = Territories.Sea("neutral", [], [], "zone_52", 0)
    zone_53 = Territories.Sea("neutral", [], [], "zone_53", 0)
    zone_54 = Territories.Sea("neutral", [], [], "zone_54", 0)
    zone_55 = Territories.Sea("neutral", [], [], "zone_55", 0)
    zone_56 = Territories.Sea("neutral", [], [], "zone_56", 0)
    zone_57 = Territories.Sea("neutral", [], [], "zone_57", 0)
    zone_58 = Territories.Sea("neutral", [], [], "zone_58", 0)
